import React from 'react';

import { Container } from './styles';

const textSample = `
quinta-feira, 13 de junho de 2019\n\nESTADO DO AMAPA\nCNPJ Nº 00.394.577/0001-25\nA/C Vinícius Carvalho\nTel: (96) 3084-8049\nE-mail: carvalho.viniciusluiz@gmail.com\n\nA empresa BUYSOFT DO BRASIL LTDA, inscrita no CNPJ nº 10.242.721/0001-61, Inscrição estadual\n90522909-50 localizada na Av. Duque de Caxias, 251 – Galeria Cezalli – Centro - CEP 87013-180 Maringá\n– PR., Fone (44) 3041-8888 Fax (44) 3041-8859, e-mail: luana.lopes@buysoft.com.br vem apresentar:\n\n                                         PROPOSTA COMERCIAL\n\nITEM          Descrição                          Quant.  Preço Unitário Preço Total                                   Marca\n\n                                                                                   R$  R$\n\n1     InDesign CC for teamsLicensing             2           6.450,00                  12.900,00 Adobe\n      Subscription New Level 1 1 – 9 – 36 meses\n\nOBS: A licença em questão é cotada em dólar, e utilizada para conversão a Ptax R$ 3,84. A Proposta\nperderá sua validade caso o dólar ultrapasse o valor de R$ 4,00\n\n      • Prazo de Entrega: até 10 dias.\n      • Pagamento: até 5 dias úteis.\n      • Prazo de Validade: 30 dias.\n      • Frete: gratuito\n      • Condições de pagamento: Transferência\n      • Banco do Brasil - Agência 1187-8 C/C:84676-7 Maringá/Paraná\n      • Nota fiscal emitida de produto (venda).\n\n*Declaramos que a Buysoft é uma revenda autorizada MICROSOFT, ADOBE, AUTODESK e KASPERSKY\n*Os preços contidos nesta proposta incluem todos os custos e despesas necessários a total execução do objeto\nora licitado, tais como, custos diretos e indiretos, tributos incidentes, taxa de administração, serviços,\nencargos sociais, trabalhistas, seguros, frete, lucro.\n*Software isento de ICMS conforme Art. 163 - Anexo V - Dec. 7871/2017 do RICMS PR. Todos os impostos\nestão inclusos, exceto valores referente DIFAL (diferencial de alíquota) ficando convencionado que, em caso\nde incidência deste tributo, será responsabilidade do adquirente o cálculo e recolhimento do mesmo,\nmediante a consulta da legislação do estado onde encontra-se sediado.\nCom a publicação do DECRETO Nº 9.412, de 18 de junho de 2018, os valores para compra direta foram\n\natualizados. O novo valor para a dispensa de licitação é de até R$ 17.600,00, válido inclusive para\n\naquisição de softwares.\n\nEncontre-nos\n\n   Central de Vendas:                    Unidade 1: Matriz e Central de Negócios   Unidade 2: Apoio Operacional\n   Capitais e Regiões Metrop. 4007-1434  Av. Duque de Caxias, 251, Galeria Cezali  Av. Dr. Chucri Zaidan, 920. 16º Andar\n   Demais Regiões 0800-6001434           Centro. - Maringá – PR                    Torre II - Vl. Cordeiro - São Paulo – SP\n   atendimento@buysoft.com.br            PABX (44) 3041-8888                       PABX (11) 4007-1434\n\n   BUYSOFT é marca registrada da BUYSOFT DO BRASIL LTDA - CNPJ: 10.242.721/0001-61 - Inscrição Estadual: 90522909-50\n
`;

export default function TextPagePanel() {
  return (
    <Container>
      <pre page="A4">{textSample}</pre>
    </Container>
  );
}
